name: releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 배포할 버전
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.version }}
        name: ${{ inputs.version }}
    - name: trigger workflow with versions
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run tag-test.yml --ref 'refs/tags/${{ inputs.version }}'
