name: releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 배포할 버전
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: create tags
      run: |
        git tag ${{ inputs.version }}
        git push --tags
        gh workflow run release.yml --ref ${{ inputs.version }}