name: Tag Test

on:
  push:
    tags:
      - "aaa-*"
  workflow_dispatch:

jobs:
  hello-world:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - id: hello
      run: |
        echo "!!!! hello world!!"
    - uses: ncipollo/release-action@v1