name: Tag Test

on:
  push:
    tags:
      - "aaa-*"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - id: hello
      run: |
        echo "!!!! hello world!!"
    - uses: ncipollo/release-action@v1